data:
  path: data/CelebA-HQ/images_512
  parquet_path: data/celebA_high.parquet
  image_size: 256
  normalize: true
  caption_path: data/captions.jsonl

checkpoint:
  path: checkpoints/test/
  ckpt_name: UNet_ckpt_test.pth
  ema_ckpt_name: UNet_ema_ckpt_test.pth

training:
  batch_size: 4
  validation_split: 0.9
  epochs: 16    
  warmup_epochs: 5
  lr: 1e-4
  grad_accum_steps: 2
  use_ema: true
  ema_beta: 0.995
  step_start_ema: 0
  num_workers: 4
  use_lpips: false
  
losses:
  lpips:
    net: vgg   

sampling:
  dir: output/samples/
  num_samples: 25
  steps: 50
  guidance_scale: 7.5

model:
  type: unet
  sample_size: 32
  in_channels: 4
  out_channels: 4
  block_out_channels: [256, 512, 1024, 1024]
  down_block_types:
    - CrossAttnDownBlock2D
    - CrossAttnDownBlock2D
    - DownBlock2D
    - DownBlock2D
  up_block_types:
    - UpBlock2D
    - UpBlock2D
    - CrossAttnUpBlock2D
    - CrossAttnUpBlock2D
  layers_per_block: 1
  cross_attention_dim: 768

scheduler:
  type: squaredcos_cap_v2
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

logs: logs/test
